#!/usr/bin/env node

var shelljs = require('shelljs');

var bangs = {
  "cpp": "http://www.cplusplus.com/search.do?q=%s",
  "ddg": "https://duckduckgo.com/?q=%s",
  "docker": "https://hub.docker.com/search/?q=%s",
  "imdb": "http://www.imdb.com/find?s=all&q=%s",
  "jquery": "https://api.jquery.com/?s=%s",
  "gh": "https://github.com/search?type=Everything&start_value=1&q=%s",
  "gl": "https://gitlab.com/search?utf8=%E2%9C%93&search=%s",
  "kat": "https://kat.cr/usearch/%s",
  "melpa": "https://melpa.org/#/?q=%s",
  "npm": "https://www.npmjs.com/search?q=%s",
  "node": "https://nodejs.org/api/%s.html",
  "rosetta": "http://rosettacode.org/mw/index.php?search=%s&go=Go",
  "so": "https://stackoverflow.com/search?q=%s",
  "t411": "https://www.t411.io/torrents/search/?search=%s",
  "tek": "https://intra.epitech.eu/user/%s",
  "tpb": "https://thepiratebay.la/search/%s/0/99/0",
  "w": "https://en.wikipedia.org/wiki/Special:Search?&go=Go&search=%s",
  "wfr": "https://fr.wikipedia.org/wiki/Special:Search?&go=Go&search=%s",
  "yt": "https://www.youtube.com/results?search_query=%s",
  "zt": "https://zone-telechargement.com/index.php?q=%s"
}
var selectedBang = null;
var query = '';

for (i in process.argv) {
  if (i < 2)
    continue;
  if (!selectedBang && bangs[process.argv[i].toLowerCase()])
    selectedBang = bangs[process.argv[i].toLowerCase()];
  else {
    if (query.length)
      query += ' ';
    query += process.argv[i];
  }
}

if (!selectedBang)
  selectedBang = bangs.ddg;

if (query.length)
  shelljs.exec('xdg-open "' + selectedBang.replace(/\%s/g, encodeURI(query)).replace('"', '\\"') + '"');
else
  shelljs.exec('xdg-open "' + selectedBang.split(/(^https?\:\/\/.*\/)/)[1] + '"');
